### ISSUE TITLE
supportsPDFs support issue

### ISSUE THREAD

**Issue by dreaken** [sugarshin/react-pdfobject#132]
Hello, how i'm able to use supportsPDFs property? 
I found, that it was implemented in #122, but im not able use PDFObject.supportsPDFs/PDFObject.supportsPDFs() as it's not detected

My package version:
"react-pdfobject": "^1.1.1",

**Comment by lvstross** [comment]
Hey @dreaken, unfortunately my changes haven't made it into a new release version of the package. @sugarshin Please publish a new version with the `supportsPDFs` method I added.

**Comment by dreaken** [comment]
@sugarshin this package is still supported? it has it been abandoned?

**Comment by sugarshin** [comment]
@dreaken Sorry for the late reply. I just published it as 1.2.0. https://www.npmjs.com/package/react-pdfobject/v/1.2.0

**Comment by dreaken** [comment]
Thank you :)
